### ISSUE TITLE
Can't login 

### ISSUE THREAD

**Issue by baraary** [BobbyESP/Jetispot#13]
I don't know for sure if it's thia is the app problem, or the issue is with Spotify itself that maybe restricted login from unofficial apps after yesterday being down, but I can't login to my account with JetiSpot. It keeps saying "Incorrect username or password", even though it's working without problem on official app or site.

I'm on Android 12.1 (L), rooted and using VPN, if any of this information can help.

**Comment by BobbyESP** [comment]
Thank you for the issue! I'm gonna take a look to it!

**Comment by BobbyESP** [comment]
Could you please tell me your region and if you are a premium user?

**Comment by baraary** [comment]
My account region is UK and yes, I'm a premium user.
As I said, I'm using VPN and tried with UK, US, Italy, France, Albania, Germany and Australia server with no luck.
I've also changed password and even signed out from all devices but none of them helped for now.

**Comment by BobbyESP** [comment]
Okay, thanks for the info. I send you a test version in the next mesaage. What arch are you using?

**Comment by BobbyESP** [comment]
https://we.tl/t-r7ZciFuzl2

**Comment by baraary** [comment]
ARM64-V8A. 
Thanks, I'll test it right now.

**Comment by BobbyESP** [comment]
Okay, you tell me!

**Comment by baraary** [comment]
Nope, didn't work. Still getting same error.

**Comment by BobbyESP** [comment]
Have you some error copied in the clipboard?

**Comment by baraary** [comment]
There's no particular error, it's just a poo-up that say's "Incorrect username or password"
Attached the screenshot:

![Screenshot_20230128-155326_Jetispot__01](https://user-images.githubusercontent.com/4853984/215266593-a6158247-3cac-417d-9c5b-b0e1c9df1fbb.png)

**Comment by BobbyESP** [comment]
The issue in this cases is the username, not the password. You can see your username here: https://www.spotify.com/en/account/overview/

Sometimes, after changing your username, Spotify keeps the old one but showing the new. Is weired.

**Comment by BobbyESP** [comment]
![IMG_20230128_133913.png](https://user-images.githubusercontent.com/60316747/215266852-cc33fd82-f478-42b9-8e97-ffdb8c6d7291.png)

**Comment by baraary** [comment]
I didn't change username at all :sweat_smile:
Anyway, I tried with both email and username, still the same.

**Comment by BobbyESP** [comment]
Hummm. So I need to investigate a bit deeper. Sorry for the inconveniences. Could you try to login without the VPN?

**Comment by baraary** [comment]
It's okay, I'm happy to help.
No, it didn't work without VPN.

FYI: I tried "iTaysonLab" version and that one has the same problem. I tried "[Pasta for Spotify](https://github.com/fennifith/Pasta-for-Spotify) " and "[Spotube](https://github.com/KRTirtho/spotube) "  apps which both using different login method and both worked fine.

**Comment by BobbyESP** [comment]
Okay! Gonna make some changes later in the login

**Comment by baraary** [comment]
Great :thumbsup:

**Comment by BobbyESP** [comment]
After some tests I'm seeing that the Spotify API is telling that your credentials are wrong. This is weired

**Comment by BobbyESP** [comment]
Did you tried login with email or username?

**Comment by baraary** [comment]
Hmmm, weird indeed. I tried with both email and username, non of them worked.

**Comment by BobbyESP** [comment]
Okay, thanks for the info

**Comment by baraary** [comment]
You're most welcome. :slightly_smiling_face:

**Comment by BobbyESP** [comment]
Hi! Could you retry to login to see if it was a server-side error?

**Comment by baraary** [comment]
Hey. I tried with both username and email. Unfortunately it didn't work.

**Comment by BobbyESP** [comment]
Okay, thank you! Did you tried to login with exactly those credentials in the official Spotify client?

**Comment by baraary** [comment]
You're welcome. Yes exactly. I tried with official Spotify client again right now to be sure and it signed in within seconds.

**Comment by BobbyESP** [comment]
Need to investigate deeper. I think it's a library problem.

**Comment by pabloscloud** [comment]
I have the same problem

**Comment by BobbyESP** [comment]
Yes, librespot-java is having some issues with the login, I either can't login. Have to fix it

**Comment by pabloscloud** [comment]
> Yes, librespot-java is having some issues with the login, I either can't login. Have to fix it

Alright

**Comment by ProtonUsing** [comment]
I am also having this issue  and would like to know how long it will take for it to be fixed if possible

**Comment by BobbyESP** [comment]
> I am also having this issue and would like to know how long it will take for it to be fixed if possible

Yesterday I have tried to make a fix but it has a lot of errors bruh

**Comment by BobbyESP** [comment]
This should be fixed in the last version.
