### ISSUE TITLE
Turkish language

### ISSUE THREAD

**Issue by senolfndk** [BobbyESP/Jetispot#16]
### Checklist

- [X] This feature is merely a UI/UX update.
- [X] This feature is not going to conflict with many of the existing options.

### Is your feature request related to a problem? Please describe.

can you add turkish language in app

**Comment by BobbyESP** [comment]
Jetispot will have a big update as soon as I can bring one to it. In there I will also make able translations

**Comment by senolfndk** [comment]
ok
