### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by TeaEndsAcronyms** [BobbyESP/Jetispot#20]
I've noticed that the last release was almost a year ago, and the app doesn't work. (keeps telling me I need premium; even tho I have premium)
Is this abandoned?

**Comment by BobbyESP** [comment]
Yeah, it's abandoned since the thing that has to be modified is from a private fork of an app dependency of the original repo owner, so sorry about that, but the owner seems to have intentions of fixing this the last days

**Comment by TeaEndsAcronyms** [comment]
> Yeah, it's abandoned since the thing that has to be modified is from a private fork of an app dependency of the original repo owner, so sorry about that, but the owner seems to have intentions of fixing this the last days

Thanks for informing me, hopefully they will fix it!

**Comment by BobbyESP** [comment]
You are welcome!
