### ISSUE TITLE
Battery Configuration

### ISSUE THREAD

**Issue by Marco-9456** [BobbyESP/Jetispot#7]
- The battery configuration button doesn't work.
- Screen record

https://user-images.githubusercontent.com/41828058/206262530-c8bc4bdb-877f-4c71-9105-a587e97d6dfa.mp4

**Comment by BobbyESP** [comment]
Thank you for the issue! I'll be taking a look to It. In Xiaomi devices It works fine, but not in my AOSP devices. I'll fix It as soon as possible.

**Comment by BobbyESP** [comment]
Fixed in new release!

**Comment by Marco-9456** [comment]
> Fixed in new release!

👍
