### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Marco-9456** [BobbyESP/Jetispot#9]
### Checklist

- [X] This feature is merely a UI/UX update.
- [X] This feature is not going to conflict with many of the existing options.

### Describe the solution you'd like

I think changing the player and the bottom navigation to something like this:

https://user-images.githubusercontent.com/41828058/206903659-40490938-6356-49f9-9efc-edd99b5e4741.mp4

Is visually better than this boxi shape:

https://user-images.githubusercontent.com/41828058/206903735-f5f8e68d-d3ed-4c06-89b7-7fd993f8ac10.mp4

### Additional context

It's not that important since the app is still in early development but i wanted to mention it before forgetting about it 😅

**Comment by BobbyESP** [comment]
Thank you for the Feature Request! I'll be adding a lot of UI changes including animations these days.
Since this week I've been having a lot of exams (I'm 16 haha), I couldn't work on the app.

**Comment by Marco-9456** [comment]
> 

Bruh, I thought you'd be 20 like me 😅
Also, good luck with your exams.

**Comment by BobbyESP** [comment]
Hahaha no problem! But yes, I'm 16 and I'm doing what is called here in Spain as "bachillerato". It's the school level that you have to do before University.

**Comment by BobbyESP** [comment]
I'm currently making some changes on the Player and also making a More Options dialog

**Comment by Marco-9456** [comment]
> I'm currently making some changes on the Player and also making a More Options dialog

Can't wait to test it 🫡

**Comment by BobbyESP** [comment]
I made some tests with Shared Animations (like moving an image from one part of the screen to other) but I wasn't able to calculate the xy cordinates correctoy so I had to rollback, but I'll be learing to make really good UI animations

**Comment by BobbyESP** [comment]
https://user-images.githubusercontent.com/60316747/208313404-c9c862e2-f809-4025-a19f-fe4ec49bf3ed.mp4

This is a preview of More Options dialog. I'll be remaking the miniplayer, adding the "likes" support, and adding/finish more options to this dialog.

**Comment by Marco-9456** [comment]
> Screenrecorder-2022-12-18-19-28-48-678.mp4
> 
> This is a preview of More Options dialog. I'll be remaking the miniplayer, adding the "likes" support, and adding/finish more options to this dialog.

This Looks pretty good
